(() => {
"use strict";

const CATALOG_URL="data/metadata/catalog.json";
const SERUMS_MANIFEST_URL="knowledge/minsa/serums-2026-ii/manifest.json";
const SERUMS_RAG_BASE="knowledge/minsa/serums-2026-ii/";
const COMPENDIA_URL="data/metadata/serums/serums-2026-ii-compendios.json";
const API=window.SIP_API||null;
const CONFIG=window.SIP_CONFIG||{MAX_QUERY_LENGTH:1200};

let catalog=null,documents=[],activeDocument=null,serumsManifest=null;
let ragReady=false,lastQuery="",activeType="",libraryState="loading";
const ragTextCache=new Map();

const $=id=>document.getElementById(id);
const arr=v=>Array.isArray(v)?v:[];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const norm=v=>String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();

function statusClass(v){v=norm(v);if(v.includes("validado_oficial"))return"ok";if(v.includes("no_aprobado"))return"warn";return"pending";}
function officialSources(doc){return arr(doc?.fuentes_oficiales);}
function officialUrl(doc){return doc?.url_oficial||officialSources(doc).find(s=>s?.url)?.url||"";}
function switchView(name){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===`view-${name}`));document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.view===name));}

function setLibraryControls(enabled){
 [$("search"),$("q"),$("searchForm")?.querySelector('button[type="submit"]'),$("queryForm")?.querySelector('button[type="submit"]')]
  .filter(Boolean).forEach(control=>{control.disabled=!enabled;});
}

function libraryStateHtml(){
 if(libraryState==="loading")return'<div class="empty-state"><strong>Cargando biblioteca…</strong><p>Espera unos segundos mientras se prepara el índice documental.</p></div>';
 return'<div class="empty-state"><strong>Biblioteca no disponible</strong><p>No se puede consultar hasta completar la carga del corpus.</p></div>';
}

function normalizedSearchText(value){
 return norm(value)
  .replace(/resolucion ministerial/g,"rm")
  .replace(/decreto supremo/g,"ds")
  .replace(/decreto legislativo/g,"dl")
  .replace(/norma tecnica de salud/g,"nts")
  .replace(/\bn\s*[.°ºo]*\s*/g," ")
  .replace(/[^a-z0-9]+/g," ")
  .replace(/\s+/g," ")
  .trim();
}

function extractNormInfo(doc){
 const source=`${doc.numero_norma||""} ${doc.resolucion_aprobatoria||""} ${doc.texto_indice||""} ${doc.titulo||""}`;
 const s=normalizedSearchText(source);
 const defs=[["NTS",/\bnts\s+(\d{1,5})(?:\s+(\d{4}))?/],["LEY",/\bley\s+(\d{1,6})(?:\s+(\d{4}))?/],["RM",/\brm\s+(\d{1,5})(?:\s+(\d{4}))?/],["DS",/\bds\s+(\d{1,5})(?:\s+(\d{4}))?/],["DL",/\bdl\s+(\d{1,5})(?:\s+(\d{4}))?/]];
 for(const [type,rx] of defs){const m=s.match(rx);if(m)return{type,number:m[1]||"",year:m[2]||""};}
 if(/\bdirectiva\b/.test(s))return{type:"DIRECTIVA",number:"",year:""};if(/\bguia\b|\bgpc\b/.test(s))return{type:"GUIA",number:"",year:""};if(/\bdocumento tecnico\b/.test(s))return{type:"DOCUMENTO TECNICO",number:"",year:""};if(/\bprotocolo\b/.test(s))return{type:"PROTOCOLO",number:"",year:""};if(/\banexo\b/.test(s))return{type:"ANEXO",number:"",year:""};return{type:"OTROS",number:"",year:""};
}
function normativeIdentifier(value){const v=normalizedSearchText(value);const m=v.match(/\b(nts|rm|ds|dl|ley)\s+(\d{1,6})(?:\s+(\d{4}))?\b/);return m?{type:m[1].toUpperCase(),number:m[2],year:m[3]||""}:null;}
function titleFromText(doc){const raw=(doc.titulo||"").trim();const generic=/^(congreso de la republica|ministerio de salud|documento oficial|norma legal|bibliografia oficial)$/i;if(raw&&!generic.test(norm(raw)))return raw;const text=String(doc._ragText||doc.texto_indice||"").replace(/\[\[PAGINA\s+\d+\]\]/gi," ").replace(/\s+/g," ").trim();if(!text)return raw||doc.id||"Documento";const parts=text.split(/(?<=[.!?])\s+/).map(x=>x.trim()).filter(x=>x.length>25&&x.length<220);return parts[0]||text.slice(0,180);}
function documentLabel(doc){const explicit=doc?.numero_norma||doc?.resolucion_aprobatoria;if(explicit)return explicit;const info=extractNormInfo(doc);if(info.number)return`${info.type} ${info.number}${info.year?`-${info.year}`:""}`;return doc?.titulo||doc?.id||"Documento";}
function renderHeader(){const total=serumsManifest?.documentos_unicos||documents.length;$("sourceCount").textContent=total;$("annexCount").textContent=documents.reduce((n,d)=>n+arr(d?.anexos_prioritarios).length,0);$("validationState").textContent=total?"BIBLIOTECA SERUMS":"—";const s=$("libraryStatus");s.textContent=total?`${total} documentos · ${serumsManifest?.compendios_descubiertos||17} compendios`:"Biblioteca no disponible";s.className=total?"status-badge":"status-badge warn";}
function renderNormButtons(){const box=$("normTypeButtons");if(!box)return;const order=["LEY","NTS","RM","DS","DL","DIRECTIVA","GUIA","PROTOCOLO","DOCUMENTO TECNICO","ANEXO","OTROS"];const counts={};documents.filter(d=>d._serumsCorpus).forEach(d=>{const t=extractNormInfo(d).type;counts[t]=(counts[t]||0)+1;});box.innerHTML=order.filter(t=>counts[t]).map(t=>`<button type="button" class="norm-filter${activeType===t?" active":""}" data-type="${esc(t)}">${esc(t)} · ${counts[t]}</button>`).join("");box.querySelectorAll(".norm-filter").forEach(b=>b.addEventListener("click",()=>{activeType=activeType===b.dataset.type?"":b.dataset.type;$("search").value="";renderNormButtons();if(activeType)renderTypeResults(activeType);else runSearch(lastQuery);}));}
function renderTypeResults(type){const list=documents.filter(d=>d._serumsCorpus&&extractNormInfo(d).type===type).sort((a,b)=>documentLabel(a).localeCompare(documentLabel(b),"es",{numeric:true}));$("result").className="results";$("result").innerHTML=list.length?list.map(d=>resultCard({doc:d,type,title:documentLabel(d),detail:titleFromText(d),state:d.estado_validacion,url:officialUrl(d),docId:d.id})).join(""):'<div class="empty-state"><strong>Sin documentos en esta categoría</strong></div>';bindResultButtons();}
function renderMetadata(){if(!activeDocument){$("metadata").innerHTML='<div class="empty-state"><strong>Sin documento activo</strong></div>';return;}const info=extractNormInfo(activeDocument),sources=officialSources(activeDocument);$("metadata").innerHTML=`<div class="metadata-grid"><article class="meta-card"><span class="eyebrow">Identificación</span><h3>${esc(documentLabel(activeDocument))}</h3><p>${esc(titleFromText(activeDocument))}</p></article><article class="meta-card"><span class="eyebrow">Clasificación</span><h3>${esc(info.type)}</h3><p>${info.number?`Número ${esc(info.number)}${info.year?` · Año ${esc(info.year)}`:""}`:"Tipo documental identificado por el corpus."}</p></article><article class="meta-card"><span class="eyebrow">Extracción</span><h3>${esc(activeDocument.metodo_extraccion||"Metadatos")}</h3><p>${activeDocument.archivo_rag?"Contenido disponible para búsqueda de texto completo.":"Documento identificado; texto completo aún no materializado."}</p></article><article class="meta-card"><span class="eyebrow">Compendio</span><h3>SERUMS 2026-II</h3><p>${esc(arr(activeDocument.compendios_origen).join(" · ")||"Bibliografía oficial MINSA")}</p></article></div><div class="trace"><b>Trazabilidad:</b> resultado → documento → página/contexto → fuente oficial.</div><div class="result-actions">${officialUrl(activeDocument)?`<a class="source-link" href="${esc(officialUrl(activeDocument))}" target="_blank" rel="noopener">Abrir fuente oficial ↗</a>`:""}${activeDocument.pdf_oficial?`<a class="source-link" href="${esc(activeDocument.pdf_oficial)}" target="_blank" rel="noopener">PDF oficial ↗</a>`:""}${sources.filter(s=>s.url&&s.url!==officialUrl(activeDocument)).map(s=>`<a class="source-link" href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.documento||"Fuente")} ↗</a>`).join("")}</div>`;}
function renderLearning(){const resources=documents.flatMap(d=>Object.values(d.recursos_pedagogicos||{}).map(r=>({...r,document:documentLabel(d)})));$("learningResources").innerHTML=resources.length?resources.map(r=>`<article class="resource-card"><span class="tag ${statusClass(r.estado)}">${esc(r.estado)}</span><h3>${esc(r.titulo)}</h3><p><b>${esc(r.document)}</b> · ${esc(r.id)}</p><p>${esc(r.motivo||"")}</p></article>`).join(""):'<div class="empty-state"><strong>Sin recursos pedagógicos cargados</strong></div>';}
function documentSearchText(doc){return [doc.id,doc.titulo,doc.numero_norma,doc.resolucion_aprobatoria,doc.texto_indice,doc.tema,doc.bloque_SERUMS,doc.institucion,doc.tipo,doc.tipo_fuente,doc._ragText,...arr(doc.subtemas),...arr(doc.compendios_origen)].filter(Boolean).join(" ");}
function pageForIndex(text,index){const before=text.slice(0,index),matches=[...before.matchAll(/\[\[PAGINA\s+(\d+)\]\]/gi)];return matches.length?matches[matches.length-1][1]:"";}
function snippetFor(doc,query){const raw=doc._ragText||"";if(!raw)return doc.archivo_rag?"Contenido completo aún cargándose.":"Coincidencia en metadatos documentales.";const terms=normalizedSearchText(query).split(/\s+/).filter(t=>t.length>1);const lowered=norm(raw);let idx=-1;for(const t of terms){idx=lowered.indexOf(t);if(idx>=0)break;}if(idx<0)return"Coincidencia en metadatos documentales.";const start=Math.max(0,idx-150),end=Math.min(raw.length,idx+300),page=pageForIndex(raw,idx);const excerpt=raw.slice(start,end).replace(/\[\[PAGINA\s+\d+\]\]/gi," ").replace(/\s+/g," ").trim();return`${page?`Página ${page} · `:""}…${excerpt}…`;}
function searchableRecords(){return documents.map(doc=>({type:doc._serumsCorpus?extractNormInfo(doc).type:"DOCUMENTO",title:documentLabel(doc),text:documentSearchText(doc),state:doc.estado_validacion,detail:titleFromText(doc),url:officialUrl(doc),docId:doc.id,doc}));}
function searchRecords(query){const q=normalizedSearchText(query),stopWords=new Set(["a","al","de","del","el","en","la","las","los","para","por","un","una","y"]);const terms=q.split(/\s+/).filter(t=>t&&!stopWords.has(t));if(!terms.length)return[];const requestedId=normativeIdentifier(query);const ranked=searchableRecords().map(r=>{const h=normalizedSearchText(`${r.title} ${r.text} ${r.detail}`);if(requestedId){const info=extractNormInfo(r.doc);const ok=info.type===requestedId.type&&info.number===requestedId.number&&(!requestedId.year||info.year===requestedId.year);if(!ok)return{...r,score:0};return{...r,score:100,detail:snippetFor(r.doc,query)};}const matched=terms.filter(t=>h.includes(t)).length,coverage=matched/terms.length;if((terms.length<=3&&coverage<1)||(terms.length>3&&coverage<.75))return{...r,score:0};const titleNorm=normalizedSearchText(`${r.title} ${r.detail}`),titleHit=terms.filter(t=>titleNorm.includes(t)).length;const originNorm=normalizedSearchText(arr(r.doc?.compendios_origen).join(" "));const originHit=terms.every(t=>originNorm.includes(t));return{...r,originHit,score:(originHit?200:0)+(coverage*10)+(titleHit*2),detail:snippetFor(r.doc,query)};}).filter(r=>r.score>0);const originMatches=ranked.filter(r=>r.originHit);return (originMatches.length?originMatches:ranked).sort((a,b)=>b.score-a.score);}
function resultCard(r){return`<article class="evidence-card"><div class="tag-row"><span class="tag">${esc(r.type)}</span>${r.state?`<span class="tag ${statusClass(r.state)}">${esc(r.state)}</span>`:""}</div><h3>${esc(r.title)}</h3><p><strong>${esc(titleFromText(r.doc||{}))}</strong></p><p>${esc(r.detail||"")}</p><div class="result-actions"><button type="button" class="open-result-doc" data-id="${esc(r.docId)}">Abrir documento</button>${r.url?`<a class="source-link" href="${esc(r.url)}" target="_blank" rel="noopener">Fuente oficial ↗</a>`:""}</div></article>`;}
function resultHtml(records,query){if(!records.length)return`<div class="empty-state"><strong>Sin coincidencias</strong><p>No se encontró “${esc(query)}” en la biblioteca disponible.</p></div>`;return records.slice(0,30).map(resultCard).join("");}
function bindResultButtons(){document.querySelectorAll(".open-result-doc").forEach(b=>b.addEventListener("click",()=>{selectDocument(b.dataset.id);switchView("source");}));}
function runSearch(query){lastQuery=String(query||"").trim();if(libraryState!=="ready"){$("result").className="results";$("result").innerHTML=libraryStateHtml();return;}activeType="";renderNormButtons();$("result").className="results";$("result").innerHTML=lastQuery?resultHtml(searchRecords(lastQuery),lastQuery):'<div class="empty-state"><strong>Biblioteca lista para consulta</strong><p>Busca por tema o selecciona un tipo de documento.</p></div>';bindResultButtons();}
function selectDocument(id){activeDocument=documents.find(d=>d.id===id)||documents[0]||null;renderMetadata();}
async function loadRagTexts(corpus){const queue=corpus.filter(d=>d.archivo_rag);let cursor=0,workers=Math.min(6,queue.length);async function worker(){while(cursor<queue.length){const d=queue[cursor++];if(ragTextCache.has(d.archivo_rag)){d._ragText=ragTextCache.get(d.archivo_rag);continue;}try{const r=await fetch(`${SERUMS_RAG_BASE}${encodeURIComponent(d.archivo_rag)}`,{cache:"force-cache"});if(r.ok){const text=await r.text();ragTextCache.set(d.archivo_rag,text);d._ragText=text;}}catch(e){console.warn("RAG no disponible",d.archivo_rag,e);}}}await Promise.all(Array.from({length:workers},worker));ragReady=true;const state=$("indexState");if(state){state.textContent="Búsqueda de contenido completo lista.";state.classList.add("ready");}renderNormButtons();if(lastQuery)runSearch(lastQuery);else if(activeType)renderTypeResults(activeType);}
async function loadCompendia(){try{const r=await fetch(COMPENDIA_URL,{cache:"no-store"});if(!r.ok)throw new Error();const data=await r.json(),box=$("serumsCompendia");box.innerHTML=arr(data.compendios).map(c=>`<button type="button" class="compendium-btn" data-query="${esc(c.nombre)}"><span><b>${esc(c.sigla)}</b><small>${esc(c.nombre)}</small></span><em>${esc(c.cantidad_normas)}</em></button>`).join("");box.querySelectorAll(".compendium-btn").forEach(btn=>btn.addEventListener("click",()=>{$("search").value=btn.dataset.query;runSearch(btn.dataset.query);}));}catch(_){$("serumsCompendia").innerHTML='<span class="muted">Compendios no disponibles.</span>';}}
function addMessage(role,title,text){const c=document.createElement("div");c.className=`message ${role}`;c.innerHTML=`<span class="avatar">${role==="user"?"TÚ":"SIP"}</span><div><strong>${esc(title)}</strong><p>${esc(text)}</p></div>`;$("out").appendChild(c);c.scrollIntoView({behavior:"smooth",block:"nearest"});}
async function assistantQuery(message){addMessage("user","Consulta",message);if(libraryState!=="ready"){addMessage("system",libraryState==="loading"?"Biblioteca cargando":"Biblioteca no disponible",libraryState==="loading"?"Espera a que termine la carga antes de consultar.":"No se pudo cargar el corpus documental.");return;}const local=searchRecords(message);if(local.length){addMessage("system","Evidencia documental",local.slice(0,5).map(r=>`${r.type}: ${r.title} — ${r.detail}`).join("\n\n"));return;}if(!API?.chat||!window.SIP_CONFIG?.API_BASE_URL){addMessage("system","EVIDENCIA_INSUFICIENTE","La biblioteca local no contiene evidencia suficiente y el backend RAG no está configurado.");return;}try{const response=await API.chat(message);addMessage("system","Respuesta RAG",response?.answer||"El backend respondió sin contenido.");}catch(e){addMessage("system","Backend no disponible",e.message);}}
async function checkBackend(){const b=$("backendStatus");if(!API?.health||!window.SIP_CONFIG?.API_BASE_URL){b.textContent="Backend pendiente";b.className="mini-status warn";return;}try{const h=await API.health();b.textContent=h?.rag_active?"RAG activo":"API activa · RAG sin índice";b.className="mini-status";}catch(_){b.textContent="Backend no disponible";b.className="mini-status warn";}}
async function loadLibrary(){try{const [catalogResponse,manifestResponse]=await Promise.all([fetch(CATALOG_URL,{cache:"no-store"}),fetch(SERUMS_MANIFEST_URL,{cache:"no-store"})]);if(!catalogResponse.ok)throw new Error(`No se pudo cargar catalog.json · HTTP ${catalogResponse.status}`);catalog=await catalogResponse.json();if(manifestResponse.ok)serumsManifest=await manifestResponse.json();const base=await Promise.all(arr(catalog.documentos).map(async item=>{try{const r=await fetch(item.ruta,{cache:"no-store"});if(!r.ok)throw new Error();const d=await r.json();if(!d.id)d.id=item.id;return d;}catch(_){return{...item,estado_validacion:item.estado||"NO_APROBADO",fuentes_oficiales:[],subtemas:[],anexos_prioritarios:[]};}}));const corpus=arr(serumsManifest?.documentos).map(d=>({...d,_serumsCorpus:true,institucion:"Ministerio de Salud del Perú",tema:"Bibliografía oficial SERUMS 2026-II",bloque_SERUMS:"SERUMS 2026-II",fuentes_oficiales:d.url_oficial?[{documento:d.titulo||d.id,url:d.url_oficial,estado_validacion:d.estado_validacion,rol_evidencia:"Fuente oficial MINSA"}]:[],subtemas:[],anexos_prioritarios:[]}));const map=new Map();[...base.filter(Boolean),...corpus].forEach(d=>{const key=d.url_oficial||officialUrl(d)||d.id;if(!map.has(key))map.set(key,d);});documents=[...map.values()];activeDocument=documents[0]||null;libraryState="ready";setLibraryControls(true);renderHeader();renderNormButtons();renderMetadata();renderLearning();loadCompendia();loadRagTexts(corpus).catch(e=>console.warn("Carga RAG parcial",e));}catch(e){libraryState="error";setLibraryControls(false);$("libraryStatus").textContent="Biblioteca no disponible";$("libraryStatus").className="status-badge warn";$("result").innerHTML=`<div class="empty-state"><strong>Error de catálogo</strong><p>${esc(e.message)}</p></div>`;}checkBackend();}
function init(){libraryState="loading";setLibraryControls(false);document.querySelectorAll(".nav-btn").forEach(b=>b.addEventListener("click",()=>switchView(b.dataset.view)));$("searchForm").addEventListener("submit",e=>{e.preventDefault();runSearch($("search").value);});$("queryForm").addEventListener("submit",e=>{e.preventDefault();const q=$("q").value.trim().slice(0,CONFIG.MAX_QUERY_LENGTH||1200);if(!q)return;$("q").value="";assistantQuery(q);});loadLibrary();}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();
